#ifndef CREDENTIALS_H
#define CREDENTIALS_H

#define WIFI_SSID "NOMBRE_RED_WIFI"
#define WIFI_PASSWORD "CONTRASEÑA_WIFI"
#define BOT_TOKEN "TOKEN_BOT_TELEGRAM"
#define CHAT_ID "ID_CHAT_TELEGRAM"
#define WEB_APP_URL "URL_WEB_APP_GOOGLE_SHEETS"

static const char * GOOGLE_ROOT_CA = \
"CERTIFICADO_ROOT_CA_GOOGLE";

static const char * TELEGRAM_ROOT_CA = \
"CERTIFICADO_ROOT_CA_TELEGRAM";

#endif